name: NGWordBAN
main: matsuo\NGWordBAN\main
version: 1.0.0
api: 3.11.0
author: matsuo877
commands:
 ngword:
   aliases:
       - ngw
   description: NGワードを登録
   usage: "/ngword 登録したいワード"
   permission: NGWordBAN.command.ngword